#!/bin/bash


THISSCRIPT=$(realpath $0)
THISDIR=$(dirname $THISSCRIPT)
cd ${HOME}/bin

for s in $(echo "vib vir mcd bak.sh os.sh")
do
  ln -s ${THISDIR}/${s} .
  echo "linked ${s}"
done

cd ${THISDIR}
